### ISSUE TITLE
Make a Golang CLI for client configuration

### ISSUE THREAD

**Issue by winwisely99** [gun1x/wireguard-mariadb-auth#2]
Just has to do what this already does:
https://github.com/gun1x/wireguard-mariadb-auth/blob/master/generate_wq-quick_config.sh

**Comment by gun1x** [comment]
Making this 100% from GoLang will be harder than it looks, because you need multiple libraries to create the interface and also configure it. I know where to search, though, and I also need the same code for the [mosquito](https://gitlab.com/spiderweber/mosquito).

I also need a GoLang CLI for the MariaDB auth, so this will probably get added in the future, but I guess you (@winwisely99) have more interest in the [spiderweber](https://gitlab.com/spiderweber) as it has gRPC, etcd and also manages multiple servers, so it fits better the scope of your project.

**Comment by gun1x** [comment]
The client will be developed [here](https://github.com/spiderweber/mosquito).

**Comment by gun1x** [comment]
All development will continue on the [spiderweber](https://github.com/spiderweber) repos. Closing this ticket.

There already is gRPC based server-client setup on those repos.
